
server:
  port: 8003
  error:
    include-stacktrace: never
  servlet:
    session:
      timeout: 600

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: info

